### ISSUE TITLE
Generate denogram given a file containing N d-dimensional vectors

### ISSUE THREAD

**Issue by frankxu2004** [yushangdi/parChain#1]
Hi thanks for the great work!

I am wondering if there are docs about how to use the tool to actually do HAC with a file of vectors, instead of benchmarking.
What are the expected input data format and what would be the output?

Thanks again!

**Comment by yushangdi** [comment]
Hi Frank, 

I create a version of the code in the "dendrogram" branch that can output the dendrogram to a file. 

the input file format is just a file of points. Each line has the coordinates of a point.
e.g. 

1.2 2.3
3.4 5.6
.....

the output is the same as the scipy dendrogram output: https://stackoverflow.com/questions/9838861/scipy-linkage-format


to output the dendrogram, you should add flag: -dendro [/name-of-output-file]

currently this does not work with flag "-matrixrange" and "-matrix". 


Please let me know if you have more questions, thanks!

Shangdi
