### ISSUE TITLE
How Dimensions affect memory and speed usage?

### ISSUE THREAD

**Issue by joancf** [yushangdi/parChain#3]
Hi Shangdi,
I have try it with the dendrogram option, 
I could run one of the sample datasets (10D_UCI1_19K) and it works
then I tried to use it with some embeddings (768 Dimensions) I had to add the code for these dimensions 
I have a dataset of 2,5M samples. (it produces an out-of-memory error) but with 1M dataset it uses 89Gb of memory (some swap) but it fails. I dies silently
this is the output:
```
+++++++++++++++
eps = 9.999999999999999451532715e-21
use matrix = 0
use matrix range = 0
naive_thresh = 5
cache_size/2 = 32
starting dendro
average Linkage of 1000000, dim 768 points
distAverage5 point array, norm = 1, rebuild tree
 ```
The command I run is this one
```
CILK_NWORKERS=12 numactl -i all ./parchain/linkage/framework/linkage -method avg -r 1 -d $DIMENSIONS -dendro ./outputs/${METHOD}/dendrogaram.txt  ./datasets/$FILE  > outputs/${METHOD}/test.txt
```
I have 16 cores, and 64G of memory

Now I have it running with only 2 workers: It  has been running for 102 hrs and seems to be able to go a bit forward, but has not ended yet!!! 
 
```
+++++++++++++++
eps = 9.999999999999999451532715e-21
use matrix = 0
use matrix range = 0
naive_thresh = 5
cache_size/2 = 32
starting dendro
average Linkage of 1000000, dim 768 points
distAverage5 point array, norm = 1, rebuild tree 2
========= CHAIN TREE =========
num workers 2
hash table size 64
::initialize: 22.557 
```

So , I would as: Is  there a way to compute the memory needed depending on?
* number of processors
* dimensionality
* dataset size
* method to compute distance

**Comment by joancf** [comment]
I have tried a smaller subset, 100K samples x 768 dimensions with 8 cores (with 12 cores it crashes): 
```
+++++++++++++++
eps = 9.999999999999999451532715e-21
use matrix = 0
use matrix range = 0
naive_thresh = 5
cache_size/2 = 32
starting dendro
average Linkage of 100000, dim 768 points
distAverage5 point array, norm = 1, rebuild tree 2
========= CHAIN TREE =========
num workers 8
hash table size 64
::initialize: 0.83097 
``` 
and after 8 x 2 hours of CPU... still running  (very slow compared to your test sets) , Which is the effect of having many dimensions? 
Shall I change some parameters like the cache or has table sizes?
Thanks

**Comment by yushangdi** [comment]
Hi Joan, 

This code works well on low dimensional datasets, but unfortunately suffers from the curse of dimensionality. This is because we uses kd-tree, and in high dimension, kd-tree searches become slow... I'd recommend running this code for datasets with <20 dimension.

**Comment by joancf** [comment]
Thanks for the information
I'll try to adapt some of your ideas for higher dimensions spaces.
